user:
  username: tomoya
  password: $2a$10$KkUG107R3ASTHfAHei.bweXWXgCa4cE1KhK.F0odzfE0r97aeeTXC  # 这个密码要用 new BCryptPasswordEncoder().encode(newPassword) 算出，如果不会用，可以用默认的，程序启动了，修改即可
  avatar: http://localhost:8080/static/images/upload/tomoya/avatar.png
  email: py2qiuse@gmail.com
  bio: hello world
  url: https://tomoya92.github.io
  role: admin
  

roles:
  -
    name: admin
    description: 超级管理员
    permissions:
      - admin:index
      - topic:edit
      - topic:delete
      - topic:top
      - topic:good
      - topic:list
      - topic:lock
      - comment:edit
      - comment:delete
      - comment:list
      - user:list
      - user:role
      - user:delete
      - user:block
      - user:unblock
      - permission:list
      - permission:add
      - permission:edit
      - permission:delete
      - role:list
      - role:add
      - role:edit
      - role:delete
      - index:all
      - index:deleteAll
      - node:list
      - node:add
      - node:edit
      - node:delete
  -
    name: banzhu
    description: 版主
    permissions:
      - admin:index
      - topic:edit
      - topic:delete
      - topic:top
      - topic:good
      - topic:list
      - topic:lock
      - comment:edit
      - comment:delete
      - comment:list
  -
    name: user
    description: 会员
    permissions:
      - topic:list
      - comment:list
permissions:
  -
    name: admin
    description: 仪表盘
    url:
    childs:
      -
        name: admin:index
        description: 后台管理
        url: /admin/index
  -
    name: topic
    description: 话题
    url:
    childs:
      -
        name: topic:edit
        description: 话题编辑
        url: /admin/topic/*/edit
      -
        name: topic:delete
        description: 话题删除
        url: /admin/topic/*/delete
      -
        name: topic:top
        description: 话题置顶
        url: /admin/topic/*/top
      -
        name: topic:good
        description: 话题加精
        url: /admin/topic/*/good
      -
        name: topic:list
        description: 话题列表
        url: /admin/topic/list
      -
        name: topic:lock
        description: 话题锁定
        url: /admin/topic/*/lock
  -
    name: comment
    description: 评论
    url:
    childs:
      -
        name: comment:edit
        description: 评论编辑
        url: /admin/comment/*/edit
      -
        name: comment:delete
        description: 评论删除
        url: /admin/comment/*/delete
      -
        name: comment:list
        description: 评论列表
        url: /admin/comment/list
  -
    name: user
    description: 用户
    url:
    childs:
      -
        name: user:list
        description: 用户列表
        url: /admin/user/list
      -
        name: user:role
        description: 用户角色
        url: /admin/user/*/role
      -
        name: user:delete
        description: 用户删除
        url: /admin/user/*/delete
      -
        name: user:block
        description: 用户禁用
        url: /admin/user/*/block
      -
        name: user:unblock
        description: 用户解禁
        url: /admin/user/*/unblock
  -
    name: permission
    description: 权限
    url:
    childs:
      -
        name: permission:list
        description: 权限列表
        url: /admin/permission/list
      -
        name: permission:add
        description: 权限添加
        url: /admin/permission/add
      -
        name: permission:edit
        description: 权限编辑
        url: /admin/permission/*/edit
      -
        name: permission:delete
        description: 权限删除
        url: /admin/permission/*/delete
  -
    name: role
    description: 角色
    url:
    childs:
      -
        name: role:list
        description: 角色列表
        url: /admin/role/list
      -
        name: role:add
        description: 角色添加
        url: /admin/role/add
      -
        name: role:edit
        description: 角色编辑
        url: /admin/role/*/edit
      -
        name: role:delete
        description: 角色删除
        url: /admin/role/*/delete
  -
    name: index
    description: 索引
    url:
    childs:
      -
        name: index:all
        description: 索引全部话题
        url: /admin/indexed/indexAll
      -
        name: index:deleteAll
        description: 删除所有索引
        url: /admin/indexed/deleteAll
  -
    name: node
    description: 节点
    url:
    childs:
      -
        name: node:list
        description: 版块列表
        url: /admin/node/list
      -
        name: node:add
        description: 添加版块
        url: /admin/node/add
      -
        name: node:edit
        description: 编辑版块
        url: /admin/node/*/edit
      -
        name: node:delete
        description: 删除版块
        url: /admin/node/*/delete