  name: vbbs
  intro: <h5>属于Java语言的bbs</h5><p>在这里，您可以提问，回答，分享，诉说，这是个属于Java程序员的社区，欢迎您的加入！</p>
  baseUrl: http://localhost:8080/ # 不要忘了后面的 '/'
  staticUrl: http://localhost:8080/static/images/upload/
  pageSize: 20
  uploadPath: ./views/${site.theme}/static/images/upload/
  theme: default
  search: true
  attempts: 5
  attemptsWaitTime: 15
  maxCreateTopic: 10
  createTopicScore: -10  # 创建主题变化的积分
  createCommentScore : -5  # 创建评论变化的积分
  userUploadSpaceSize: 50 # 单位MB
  score: 2000 # 用户注册后初始积分
  loginPoints: 2 # 登录点，最多2个位置登录，第三个登录点会覆盖第一个
  GA: #Google Analytics ID
  googleZZ: # google站长meta标签content值
  baiduTJ: # 百度统计ID
  baiduZZ: # 百度站长meta标签content值
  ssl: false # 网站重写向是否转到https上，默认是否，如果你网站开启了https，请把这个设置为true
  newUserRole: user # 这里跟data.yml里的 _roles 里配置的角色名字要一
  cookie:
    domain: localhost
    attendanceMaxAge: 86400
    attendanceName: attendance
    rememberMeExpireDay: 30 # 记住我30天
  mail:
    subject: 注册验证码 - ${site.name}
    content: |
          <p>您好</p>
          <p>&nbsp;&nbsp;您的验证码为 <span style='color: red;'>${genCode}</span> , 请在10分钟内使用！</p><br>
          <small>本邮件为系统发出，请不要评论</small>
  illegalUsername:
    - profile
    - changeAvatar
    - changePassword
    - accessToken
    - refreshToken
    - space
    - scoreLog
  scoreTemplate:
    dailySign: 每日签到获得${scoreLog.changeScore}积分
    createTopic: 发表主题[<a href="/topic/${topic.id?c}" target="_blank">${topic.title?html}</a>],扣减${scoreLog.changeScore}积分
    commentTopic: 评论主题[<a href="/topic/${topic.id?c}"  target="_blank">${topic.title?html}</a>],扣减${scoreLog.changeScore}积分
    register: 用户注册奖励${scoreLog.changeScore}积分